package models

type AutoGenerated3 struct {
	Uvd struct {
		Login  bool   `json:"login"`
		Ov     int    `json:"ov"`
		Sb     int    `json:"sb"`
		UrView string `json:"urView"`
		Efloat bool   `json:"efloat"`
		Showls bool   `json:"showls"`
		Nol    int    `json:"nol"`
		Iarf   bool   `json:"iarf"`
		Pds    int    `json:"pds"`
	} `json:"uvd"`
	Lpd struct {
		Sm struct {
			Fe struct {
				Progms []interface{} `json:"progms"`
			} `json:"fe"`
			Smd []struct {
				Sid  int    `json:"sid"`
				Sn   string `json:"sn"`
				Sen  string `json:"sen"`
				Mt   int    `json:"mt"`
				Son  int    `json:"son"`
				Tc   int    `json:"tc"`
				Tmrc int    `json:"tmrc"`
				Ipc  int    `json:"ipc"`
				Ec   int    `json:"ec"`
				Psc  int    `json:"psc"`
				Orc  int    `json:"orc"`
				Eec  int    `json:"eec"`
				Puc  []struct {
					Ces []interface{} `json:"ces"`
					Cid int           `json:"cid"`
					Cn  string        `json:"cn"`
					Cen string        `json:"cen"`
				} `json:"puc"`
				Pc int `json:"pc"`
			} `json:"smd"`
			V  int           `json:"v"`
			Fv int           `json:"fv"`
			Mc []interface{} `json:"mc"`
		} `json:"sm"`
		Ips struct {
			Ismd []struct {
				Sid  int    `json:"sid"`
				Sn   string `json:"sn"`
				Sen  string `json:"sen"`
				Mt   int    `json:"mt"`
				Son  int    `json:"son"`
				Tc   int    `json:"tc"`
				Tmrc int    `json:"tmrc"`
				Ipc  int    `json:"ipc"`
				Ec   int    `json:"ec"`
				Psc  int    `json:"psc"`
				Orc  int    `json:"orc"`
				Eec  int    `json:"eec"`
				Puc  []struct {
					Ces []struct {
						Eid  int    `json:"eid"`
						En   string `json:"en"`
						Gt   string `json:"gt"`
						Tid  string `json:"tid"`
						Ior  bool   `json:"ior"`
						Ht   string `json:"ht"`
						At   string `json:"at"`
						Ipt  string `json:"ipt"`
						Etts string `json:"etts"`
						Hs   struct {
							V string `json:"v"`
						} `json:"hs"`
						As struct {
							V string `json:"v"`
						} `json:"as"`
						Il   bool   `json:"il"`
						Mts  int    `json:"mts"`
						Isbg bool   `json:"isbg"`
						Lts  string `json:"lts"`
						Pt   int    `json:"pt"`
						Isb  bool   `json:"isb"`
					} `json:"ces"`
					Cid int    `json:"cid"`
					Cn  string `json:"cn"`
				} `json:"puc"`
				Pc int `json:"pc"`
			} `json:"ismd"`
			V int `json:"v"`
		} `json:"ips"`
		Ssm struct {
			Ssmd []struct {
				Sid  int    `json:"sid"`
				Sn   string `json:"sn"`
				Sen  string `json:"sen"`
				Mt   int    `json:"mt"`
				Son  int    `json:"son"`
				Tc   int    `json:"tc"`
				Tmrc int    `json:"tmrc"`
				Ipc  int    `json:"ipc"`
				Ec   int    `json:"ec"`
				Psc  int    `json:"psc"`
				Orc  int    `json:"orc"`
				Eec  int    `json:"eec"`
				Puc  []struct {
					Ces []struct {
						Eid int    `json:"eid"`
						Gt  string `json:"gt"`
						Tid string `json:"tid"`
						Ior bool   `json:"ior"`
						Ht  string `json:"ht"`
						At  string `json:"at"`
						Est string `json:"est"`
						Hs  struct {
						} `json:"hs"`
						As struct {
						} `json:"as"`
						Il   bool `json:"il"`
						Mts  int  `json:"mts"`
						Isbg bool `json:"isbg"`
						Pt   int  `json:"pt"`
						Isb  bool `json:"isb"`
					} `json:"ces"`
					Cid int    `json:"cid"`
					Cn  string `json:"cn"`
					Cen string `json:"cen"`
				} `json:"puc"`
				Pc int `json:"pc"`
			} `json:"ssmd"`
			V int `json:"v"`
		} `json:"ssm"`
		Psm struct {
			Psmd []struct {
				Sid  int    `json:"sid"`
				Sn   string `json:"sn"`
				Sen  string `json:"sen"`
				Mt   int    `json:"mt"`
				Son  int    `json:"son"`
				Tc   int    `json:"tc"`
				Tmrc int    `json:"tmrc"`
				Ipc  int    `json:"ipc"`
				Ec   int    `json:"ec"`
				Psc  int    `json:"psc"`
				Orc  int    `json:"orc"`
				Eec  int    `json:"eec"`
				Puc  []struct {
					Ces []struct {
						Eid int    `json:"eid"`
						En  string `json:"en"`
						Gt  string `json:"gt"`
						Tid string `json:"tid"`
						Ior bool   `json:"ior"`
						Ht  string `json:"ht"`
						At  string `json:"at"`
						Esd string `json:"esd"`
						Est string `json:"est"`
						Hs  struct {
						} `json:"hs"`
						As struct {
						} `json:"as"`
						Il   bool `json:"il"`
						Mts  int  `json:"mts"`
						Isbg bool `json:"isbg"`
						Pt   int  `json:"pt"`
						Isb  bool `json:"isb"`
					} `json:"ces"`
					Cid int    `json:"cid"`
					Cn  string `json:"cn"`
				} `json:"puc"`
				Pc int `json:"pc"`
			} `json:"psmd"`
			V int `json:"v"`
		} `json:"psm"`
		Tipc int `json:"tipc"`
		Tssc int `json:"tssc"`
		Tpc  int `json:"tpc"`
	} `json:"lpd"`
	Lpc struct {
		Sm  int `json:"sm"`
		Smv int `json:"smv"`
		Imv int `json:"imv"`
		Ssv int `json:"ssv"`
	} `json:"lpc"`
	Mpc struct {
		Pv int `json:"pv"`
	} `json:"mpc"`
	Mod struct {
		D []struct {
			K  int    `json:"k"`
			Tn string `json:"tn"`
			Bt string `json:"bt"`
			V  int    `json:"v"`
			C  []struct {
				K int    `json:"k"`
				N string `json:"n"`
				E []struct {
					HasParlay bool   `json:"hasParlay"`
					Hide      bool   `json:"hide"`
					Egn       string `json:"egn"`
					K         int    `json:"k"`
					Heid      int    `json:"heid"`
					L         int    `json:"l"`
					O         struct {
						Ah       []string   `json:"ah"`
						Ou       []string   `json:"ou"`
						OneX2    []string   `json:"1x2"`
						Oe       []string   `json:"oe"`
						Ah1St    []string   `json:"ah1st"`
						Ou1St    []string   `json:"ou1st"`
						OneX21St []string   `json:"1x21st"`
						Oe1St    []string   `json:"oe1st"`
						Tg       []string   `json:"tg"`
						Cs       []string   `json:"cs"`
						Hf       []string   `json:"hf"`
						Tg1St    []string   `json:"tg1st"`
						Cs1St    []string   `json:"cs1st"`
						Tts1St   []string   `json:"tts1st"`
						Ttslast  []string   `json:"ttslast"`
						Sco1St   []string   `json:"sco1st"`
						Scolast  []string   `json:"scolast"`
						Bts      [][]string `json:"bts"`
						Eps      struct {
							N         string     `json:"n"`
							Mn        string     `json:"mn"`
							F         string     `json:"f"`
							O         [][]string `json:"o"`
							Mo        int        `json:"mo"`
							Expnd     bool       `json:"expnd"`
							CanParlay bool       `json:"canParlay"`
						} `json:"eps"`
					} `json:"o"`
					Pts  []interface{} `json:"pts"`
					Ibs  bool          `json:"ibs"`
					Ibsc bool          `json:"ibsc"`
					Mltv struct {
						Vp    string `json:"vp"`
						Chkbb bool   `json:"chkbb"`
					} `json:"mltv"`
					Cel []struct {
						HasParlay bool   `json:"hasParlay"`
						Hide      bool   `json:"hide"`
						Egn       string `json:"egn"`
						K         int    `json:"k"`
						Heid      int    `json:"heid"`
						L         int    `json:"l"`
						O         struct {
							Ah       []string `json:"ah"`
							Ou       []string `json:"ou"`
							OneX2    []string `json:"1x2"`
							Oe       []string `json:"oe"`
							Ah1St    []string `json:"ah1st"`
							Ou1St    []string `json:"ou1st"`
							OneX21St []string `json:"1x21st"`
							Oe1St    []string `json:"oe1st"`
						} `json:"o"`
						NO   []interface{} `json:"n-o"`
						Pts  []interface{} `json:"pts"`
						Ibs  bool          `json:"ibs"`
						Ibsc bool          `json:"ibsc"`
						Mltv struct {
							Chkbb bool `json:"chkbb"`
						} `json:"mltv"`
						Cel []interface{} `json:"cel"`
						Cei struct {
							Ctid int    `json:"ctid"`
							N    string `json:"n"`
						} `json:"cei"`
						Pk   string   `json:"pk"`
						Ihe  bool     `json:"ihe"`
						G    string   `json:"g"`
						I    []string `json:"i"`
						Edt  string   `json:"edt"`
						Pvdr string   `json:"pvdr"`
						Mts  int      `json:"mts"`
					} `json:"cel"`
					Cei struct {
						Ctid int    `json:"ctid"`
						N    string `json:"n"`
					} `json:"cei"`
					Pk   string   `json:"pk"`
					Ihe  bool     `json:"ihe"`
					G    string   `json:"g"`
					I    []string `json:"i"`
					Edt  string   `json:"edt"`
					Pvdr string   `json:"pvdr"`
					Mts  int      `json:"mts"`
				} `json:"e"`
				Ec    int  `json:"ec"`
				Hasor bool `json:"hasor"`
			} `json:"c"`
			N   string `json:"n"`
			En  string `json:"en"`
			Hem bool   `json:"hem"`
		} `json:"d"`
		Bt []struct {
			N  string `json:"n"`
			C  int    `json:"c"`
			K  string `json:"k"`
			Sk string `json:"sk"`
		} `json:"bt"`
		Ec   int `json:"ec"`
		Tthi int `json:"tthi"`
		Spec struct {
			Ie int `json:"ie"`
			Te int `json:"te"`
			Fe int `json:"fe"`
			Oe int `json:"oe"`
		} `json:"spec"`
		T int `json:"t"`
		P struct {
			C int `json:"c"`
			T int `json:"t"`
		} `json:"p"`
		R int `json:"r"`
	} `json:"mod"`
	Selobj struct {
		Pid  int    `json:"pid"`
		Isp  bool   `json:"isp"`
		Spt  int    `json:"spt"`
		Sptn string `json:"sptn"`
		Evt  int    `json:"evt"`
		Cids string `json:"cids"`
		Gid  string `json:"gid"`
		Dp   int    `json:"dp"`
		FavT int    `json:"favT"`
		Btp  string `json:"btp"`
		Tab  string `json:"tab"`
		Uibt string `json:"uibt"`
		Edt  string `json:"edt"`
		Isfd bool   `json:"isfd"`
		IP   bool   `json:"ip"`
		Ipo  bool   `json:"ipo"`
		Dts  []struct {
			URL         string `json:"Url"`
			Date        string `json:"Date"`
			IsSelect    bool   `json:"IsSelect"`
			EventCount  int    `json:"EventCount"`
			DisplayDate string `json:"DisplayDate"`
		} `json:"dts"`
		Ifl bool `json:"ifl"`
	} `json:"selobj"`
}
