package models

//体育运动
type Smd struct {
	Sid  int    `gorm:"primary_key" json:"sid"`
	Sn   string `json:"sn"`  //中文名字
	Sen  string `json:"sen"` //英文
	Mt   int    `json:"mt"`
	Son  int    `json:"son"` //排序
	Tc   int    `json:"tc"`
	Tmrc int    `json:"tmrc"`
	Ipc  int    `json:"ipc"`
	Ec   int    `json:"ec"`
	Psc  int    `json:"psc"`
	Orc  int    `json:"orc"`
	Eec  int    `json:"eec"`
	Puc  []Puc  `json:"puc"`
	Pc   int    `json:"pc"`
}

//什么赛事（欧洲杯，世界杯）
type Puc struct {
	Ces []Ces  `json:"ces"`
	Cid int    `json:"cid"`
	Cn  string `json:"cn"`
	Cen string `json:"cen"`
}

//什么比赛
type Ces struct {
	Eid  int      `json:"eid"`
	En   string   `json:"en"`
	Gt   string   `json:"gt"`
	Tid  string   `json:"tid"`
	Ior  bool     `json:"ior"`
	Ht   string   `json:"ht"`
	At   string   `json:"at"`
	Esd  string   `json:"esd"`
	Est  string   `json:"est"`
	Hs   struct{} `json:"hs"`
	As   struct{} `json:"as"`
	Il   bool     `json:"il"`
	Mts  int      `json:"mts"`
	Isbg bool     `json:"isbg"`
	Pt   int      `json:"pt"`
	Isb  bool     `json:"isb"`
}

//球队
type M struct {
	Spid  int      `json:"spid"`
	Sid   int      `json:"sid"`
	Sn    string   `json:"sn"`
	C     struct{} `json:"c"`
	K     int      `json:"k"`
	Img   string   `json:"img"`
	T     int      `json:"t"`
	Dv    int      `json:"dv"`
	Tt    int      `json:"tt"`
	Idm   bool     `json:"idm"`
	Msg   string   `json:"msg"`
	Rd    string   `json:"rd"`
	IP    bool     `json:"ip"`
	IsEpm bool     `json:"isEpm"`
}

type S struct {
	Spid  int    `json:"spid"`
	Sid   int    `json:"sid"`
	Sn    string `json:"sn"`
	C     []C    `json:"c"`
	K     int    `json:"k"`
	Img   string `json:"img"`
	T     int    `json:"t"`
	Dv    int    `json:"dv"`
	Tt    int    `json:"tt"`
	Idm   bool   `json:"idm"`
	Msg   string `json:"msg"`
	Rd    string `json:"rd"`
	IP    bool   `json:"ip"`
	IsEpm bool   `json:"isEpm"`
}

type C struct {
	Hasor  bool   `json:"hasor"`
	Hasepm bool   `json:"hasepm"`
	K      int    `json:"k"`
	E      []E    `json:"e"`
	N      string `json:"n"`
	Ec     int    `json:"ec"`
}

type E struct {
	Mts  int      `json:"mts"`
	K    int      `json:"k"`
	Pk   int      `json:"pk"`
	Edt  string   `json:"edt"`
	Egn  string   `json:"egn"`
	IP   bool     `json:"ip"`
	No   []No     `json:"n-o"`
	O    struct{} `json:"o"`
	Hide bool     `json:"hide"`
	G    string   `json:"g"`
	Cel  []Cel    `json:"cel"`
	Cei  struct {
		Ctid int    `json:"ctid"`
		N    string `json:"n"`
	} `json:"cei"`
	I    []string `json:"i"`
	Pvdr string   `json:"pvdr"`
	Ibs  bool     `json:"ibs"`
	Ibsc bool     `json:"ibsc"`
	Ihe  bool     `json:"ihe"`
	Heid int      `json:"heid"`
	Iscc bool     `json:"iscc"`
}

type Cel []struct {
	Mts  int           `json:"mts"`
	K    int           `json:"k"`
	Pk   int           `json:"pk"`
	Edt  string        `json:"edt"`
	Egn  string        `json:"egn"`
	IP   bool          `json:"ip"`
	NO   []No          `json:"n-o"`
	O    O             `json:"o"`
	Hide bool          `json:"hide"`
	G    string        `json:"g"`
	Cel  []interface{} `json:"cel"`
	Cei  struct {
		Ctid int    `json:"ctid"`
		N    string `json:"n"`
	} `json:"cei"`
	I    []string `json:"i"`
	Pvdr string   `json:"pvdr"`
	Ibs  bool     `json:"ibs"`
	Ibsc bool     `json:"ibsc"`
	Ihe  bool     `json:"ihe"`
	Heid int      `json:"heid"`
	Iscc bool     `json:"iscc"`
}

type AutoGenerated struct {
	HasParlay bool          `json:"hasParlay"`
	Hide      bool          `json:"hide"`
	Egn       string        `json:"egn"`
	K         int           `json:"k"`
	Heid      int           `json:"heid"`
	L         int           `json:"l"`
	O         O             `json:"o"`
	NO        []interface{} `json:"n-o"`
	Pts       []interface{} `json:"pts"`
	Ibs       bool          `json:"ibs"`
	Ibsc      bool          `json:"ibsc"`
	Mltv      struct {
		Chkbb bool `json:"chkbb"`
	} `json:"mltv"`
	Cel []interface{} `json:"cel"`
	Cei struct {
		Ctid int    `json:"ctid"`
		N    string `json:"n"`
	} `json:"cei"`
	Pk   string   `json:"pk"`
	Ihe  bool     `json:"ihe"`
	G    string   `json:"g"`
	I    []string `json:"i"`
	Edt  string   `json:"edt"`
	Pvdr string   `json:"pvdr"`
	Mts  int      `json:"mts"`
}

type No struct {
	N         string     `json:"n"`
	Mn        string     `json:"mn"`
	O         [][]string `json:"o"`
	Mo        int        `json:"mo"`
	Expnd     bool       `json:"expnd"`
	CanParlay bool       `json:"canParlay"`
}

type O struct {
	Ah       []string `json:"ah"`
	Ou       []string `json:"ou"`
	OneX2    []string `json:"1x2"`
	Oe       []string `json:"oe"`
	Ah1St    []string `json:"ah1st"`
	Ou1St    []string `json:"ou1st"`
	OneX21St []string `json:"1x21st"`
	Oe1St    []string `json:"oe1st"`
}

type O_1 struct {
	Ah       []string   `json:"ah"`
	Ou       []string   `json:"ou"`
	OneX2    []string   `json:"1x2"`
	Oe       []string   `json:"oe"`
	Ah1St    []string   `json:"ah1st"`
	Ou1St    []string   `json:"ou1st"`
	OneX21St []string   `json:"1x21st"`
	Oe1St    []string   `json:"oe1st"`
	Tg       []string   `json:"tg"`
	Cs       []string   `json:"cs"`
	Hf       []string   `json:"hf"`
	Tg1St    []string   `json:"tg1st"`
	Cs1St    []string   `json:"cs1st"`
	Tts1St   []string   `json:"tts1st"`
	Ttslast  []string   `json:"ttslast"`
	Sco1St   []string   `json:"sco1st"`
	Scolast  []string   `json:"scolast"`
	Bts      [][]string `json:"bts"`
	Eps      struct {
		N         string     `json:"n"`
		Mn        string     `json:"mn"`
		F         string     `json:"f"`
		O         [][]string `json:"o"`
		Mo        int        `json:"mo"`
		Expnd     bool       `json:"expnd"`
		CanParlay bool       `json:"canParlay"`
	} `json:"eps"`
}
